// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoMm_CMHsPwanDhFitTNp8cYlAoz5yjVE',
    appId: '1:296039717564:web:41e65fd5d92390a4614eb9',
    messagingSenderId: '296039717564',
    projectId: 'chrome-hearts-uts',
    authDomain: 'chrome-hearts-uts.firebaseapp.com',
    storageBucket: 'chrome-hearts-uts.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Jri3Km4_5xo7EkQEtxZ4hIDu-mcUoxw',
    appId: '1:296039717564:android:9070dafa959c842f614eb9',
    messagingSenderId: '296039717564',
    projectId: 'chrome-hearts-uts',
    storageBucket: 'chrome-hearts-uts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5OupaCDvaNMwC2xg01z4RhJ53fxBXDc',
    appId: '1:296039717564:ios:e8bd7d02bdd23c59614eb9',
    messagingSenderId: '296039717564',
    projectId: 'chrome-hearts-uts',
    storageBucket: 'chrome-hearts-uts.firebasestorage.app',
    iosClientId: '296039717564-joppsdpet2h4gop67ntkgi757ebori25.apps.googleusercontent.com',
    iosBundleId: 'com.example.chromeHearts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX5OupaCDvaNMwC2xg01z4RhJ53fxBXDc',
    appId: '1:296039717564:ios:e8bd7d02bdd23c59614eb9',
    messagingSenderId: '296039717564',
    projectId: 'chrome-hearts-uts',
    storageBucket: 'chrome-hearts-uts.firebasestorage.app',
    iosClientId: '296039717564-joppsdpet2h4gop67ntkgi757ebori25.apps.googleusercontent.com',
    iosBundleId: 'com.example.chromeHearts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoMm_CMHsPwanDhFitTNp8cYlAoz5yjVE',
    appId: '1:296039717564:web:6c50dd2b696b7bda614eb9',
    messagingSenderId: '296039717564',
    projectId: 'chrome-hearts-uts',
    authDomain: 'chrome-hearts-uts.firebaseapp.com',
    storageBucket: 'chrome-hearts-uts.firebasestorage.app',
  );
}
